# Generated by Django 5.0.2 on 2024-02-11 17:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup', models.CharField(max_length=200)),
                ('pickup_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_contact_no', models.CharField(max_length=30)),
                ('dropoff', models.CharField(max_length=200)),
                ('recipient_name', models.CharField(max_length=100)),
                ('recipient_contact_no', models.CharField(max_length=30)),
                ('parcel_type', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('courier_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payment_type', models.CharField(max_length=30)),
                ('booked_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=20)),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-booked_date'],
            },
        ),
    ]
